Company controllermongo
AlexisPucheta/caldar-be pull request #20
Opened 2020-12-02 01:02 UTC by marcosjmelgar

2020-12-02 01:07 UTC, AlexisPucheta requested changes

2020-12-02 01:07 UTC, AlexisPucheta commented on models/company.js
> +}, {timestamps: true });
te falta el _id: true, es para cuando creas un documento mongodb le asigne un id objectID

2020-12-02 01:20 UTC, AlexisPucheta approved these changes

2020-12-02 01:24 UTC, AlexisPucheta requested changes

2020-12-02 01:24 UTC, AlexisPucheta commented on controllers/company.js
> +const { json } = require('express');
las tres primeras lineas no van, debiera ir algo asi: const Technician = require("../models/technician");

2020-12-02 01:41 UTC, AlexisPucheta approved these changes

2020-12-02 11:45 UTC, frandk18 approved these changes
Me pareció haber visto comentarios que quedaron en el controller company.js. Para la próxima borrar todo comentario que no sea necesario, es decir, si habías comentado un corcho de código y desp no lo volviste a usar, se limpia. 
Repito me pareció haberlo visto, tal vez estoy equivocado, de ser así desestimar.

2020-12-03 12:26 UTC, fjmorabito approved these changes

2020-12-03 13:37 UTC, AlexisPucheta approved these changes

2020-12-03 13:43 UTC, merged